spring:
  application:
    name: greeting
 
management:
  security:
    enabled: false
 
greeting:
  displayFortune: true
 
fortune:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2